### ISSUE TITLE
Question: RefinerAlgorithms and associated DataFactories

### ISSUE THREAD

**Issue by PhilipDeegan** [LLNL/SAMRAI#106]
Hi there,

We've found that when registering refiners via SAMRAI::xfer::RefineAlgorithm::registerRefine, in order to later use the DataFactory associated with each registered item, we needed to have distinct VariableFillPattern types passed in, per type. Otherwise only the DataFactory of the first registered item is used for all items.

Is this the correct method to have this functionality?

Thanks

**Comment by nicolasaunai** [comment]
See 

https://github.com/PHAREHUB/PHARE/blob/master/src/amr/messengers/quantity_communicator.h#L31-L49

and

https://github.com/PHAREHUB/PHARE/blob/master/src/amr/messengers/quantity_communicator.h#L177-L193

as a concrete example.

**Comment by nselliott** [comment]
There is an "equivalence class" check when registerRefine is called multiple times on a RefineAlgorithm.  Two items registered with the RefineAlgorithm are considered equivalent if all of their data have the same datatype, the same ghost width, and the RefineOperators have the same stencil width, and the VariableFillPatterns are the same type.

All items that are determined to be equivalent are placed in an equivalence class, and then only the factories from the first registered item are used to do some of the mesh overlap calculations during the construction of the RefineSchedules.  The intent here is to reduce overhead because these calculations will produce identical results for each equivalent item, so we can invoke them once and apply the results to all of the items.

Your workaround in the code example forces them to be non-equivalent by creating new VariableFillPattern datatypes, so the RefineSchedule will do the overlap calculations separately for each item.  Does your code not work if you don't use this workaround?  If your (x,y,z) vector components all are defined with the same geometric properties, then things should work as I described, but it's possible that the equivalence class check is missing something that is exposed by your code.

**Comment by nicolasaunai** [comment]
Hi, thanks for your answer.
I'm afraid no, the code breaks if we do not create the empty VariableFillPaterns for each call to registerRefine.

The main reason is that in our code we separate the geometry from the data container. Our data container (https://github.com/PHAREHUB/PHARE/blob/master/src/core/data/field/field.h#L27) has a tag coding which physical quantity it holds. The geometry is handled by another object (https://github.com/PHAREHUB/PHARE/blob/master/src/core/data/grid/gridlayout.h#L65) which is basically a map from physical quantity to data layout on the mesh. Code manipulating `Field` use the `GridLayout` object to get grid related info or perform grid related computations (such as derivatives).

This separation between data and geometry enables to change the data layout (at compile time) without changing the code using the data.

In our code thus, all grid based physical quantities, no matter where they are defined on the mesh, are contained in a `Field`. Our concrete `PatchData` is called a `FieldData` (https://github.com/PHAREHUB/PHARE/blob/master/src/amr/data/field/field_data.h) and basically encapsulate a `Field` and a `GridLayout` to provide all functionalities (data container + geometry) needed by `PatchData`.

Similarly, we have only one RefineOperator specialization : the `FieldDataOperator` (https://github.com/PHAREHUB/PHARE/blob/master/src/amr/data/field/refine/field_refine_operator.h#L26), etc.

So we end up registering different quantities that all look the same from the RefineAlgorithm point of view... hence the need for the work around.

We just wanted to understand whether this was a viable method... because we had to dig a little bit into SAMRAI's code to find it out.
