### ISSUE TITLE
do overlap used in refine Schedules consider patch datas of the same patch

### ISSUE THREAD

**Issue by nicolasaunai** [LLNL/SAMRAI#120]
Hi,

We use this overload of createSchedule to fill ghosts : 

```

   std::shared_ptr<RefineSchedule>
   createSchedule(
      const std::shared_ptr<hier::PatchLevel>& level,
      const int next_coarser_level,
      const std::shared_ptr<hier::PatchHierarchy>& hierarchy,
      RefinePatchStrategy* patch_strategy = 0,
      bool use_time_interpolation = false,
      const std::shared_ptr<RefineTransactionFactory>& transaction_factory =
         std::shared_ptr<RefineTransactionFactory>());

```

doc says:

```
    * Data will be communicated from the interiors of the source data on
    * on the given level to the interiors and ghosts of destination data on
    * the same level where those sources and destinations overlap.  Where they
    * do not overlap, data will be interpolated from source data on coarser
    * levels in the patch hierarchy.
```

my patches are adjacent so the overlap between the neighbor patch box and my ghost box is only the ghost nodes.

When using this schedule from an algorithm where the source and destination patch data are from the same variable, I get the overlap that indeed only covers the current patch data ghost nodes.

However when filling ghosts of one PatchData from another variable, it seems I'm getting overlap that cover the entire box.

I've always understood the doc as if the schedule was looking for data in _**other**_ patches of the same level and if not would refine from next coarser. But it appears actually that SAMRAI looks for overlap with the source patch_data even if it is on the same Patch ?

is there a way to exclude the patch from which the patch data to be filled is from the overlap calculation ?

**Comment by nselliott** [comment]
The default behavior of createSchedule is to create all possible overlaps between source and destination data, so this does indeed include overlaps from the interior of a patch to itself.  There is one exception which you have mentioned, if the source and destination data are the same data then the overlaps from a patch to itself are excluded, because a data copy in that situation would be a null operation.

We do have a way to modify this behavior, using the class PatchLevelFillPattern.  This is an abstract base class that provides a way to add restrictions on the parts of a destination level where overlaps will be created in a RefineSchedule.  To use this, you must use a different overloaded version of createSchedule.

`   std::shared_ptr<RefineSchedule>
   createSchedule(
      const std::shared_ptr<PatchLevelFillPattern>& fill_pattern,
      const std::shared_ptr<hier::PatchLevel>& level,
      const int next_coarser_level,
      const std::shared_ptr<hier::PatchHierarchy>& hierarchy,
      RefinePatchStrategy* patch_strategy = 0,
      bool use_time_interpolation = false,
      const std::shared_ptr<RefineTransactionFactory>& transaction_factory =
         std::shared_ptr<RefineTransactionFactory>());
`
We have several child class implementations of PatchLevelFillPattern in the SAMRAI library, but not one that does exactly what you describe, to create overlaps over all ghost regions on the destination while excluding all destination patch interiors.  You would need to create your own child class to do this.  If you need some advice on implementing this class, please let me know.

**Comment by nicolasaunai** [comment]
Thanks for you quick response. It wasn't really clear to me whether PatchLevelFillPattern or variableFillPattern should be use, as both seem to somehow restrict the parts of the destination that are filled. My understanding is that the PatchLevelFillPattern is used to discard some regions in the level for overlap calculation while the second is used downstream once these overlaps are calculated, to restrict them, correct?
So what we'd need, as you say, to fill all patch ghosts but discarding the patch interiors would be somehow the opposite of PatchLevelInteriorFillPattern, some kind of PatchLevelPatchGhostFillPattern, that would compute overlaps only in patch ghosts, excluding patch interiors, and possibly excluding level ghosts.

Second question, in the registerRefine overload that takes the timeRefinementOperator, one needs the src and dest, but also the src_tnew and src_told. If I use the same ID for src and new, but two other for src_tnew and src_told, what should I expect? Here src and dest are the same so would the overlap exclude destination patch interiors?

**Comment by nselliott** [comment]
The VariableFillPattern is another way to create restrictions on the overlaps for the destination filling.  The difference is that VariableFillPattern can be used to place different restrictions on each variable, and those restrictions can take into account the data layout and centering of various PatchData types.  The VariableFillPattern is specified in the registerRefine() calls, so a variety of VariableFillPatterns can be registered with one instance of RefineAlgorithm.  PatchLevelFillPattern is used to place more broad restrictions based on the characteristics of the patches or the level, and those restrictions apply to all variables in a RefineSchedule.

You have exactly the right idea of having an implementation that's the opposite of PatchLevelInteriorFillPattern.  If you still want interpolation from the coarser level at the level ghosts, then you need to include those ghosts, otherwise you could exclude them.

All of my comments here apply equally to the registerRefine operations that use time refinement and those that don't.  If the source and destination data are the same, then the overlaps from a patch to itself will be excluded.  If they are different, the overlaps will be included.

**Comment by nicolasaunai** [comment]
ok and it seems that if source == destination, then even if old and new are different patch IDs, the overlap are calculated as I expect, so that's ok.
Thanks!
