### ISSUE TITLE
no geometry on temporary patches?

### ISSUE THREAD

**Issue by nicolasaunai** [LLNL/SAMRAI#147]
Our override of PatchData encapsulates geometrical properties that are constructed by inspecting the PatchGeometry

https://github.com/PHAREHUB/PHARE/blob/master/src/amr/data/field/field_data_factory.h#L73 
https://github.com/PHAREHUB/PHARE/blob/master/src/amr/resources_manager/amr_utils.h#L165

As you can see, we inspect whether the geometry pointer is nullptr and if yes we throw.
We have discovered that when executed with MPI, the exception is triggered. This comes from the fact that the given patch is a temporary patch made in RefineTimeTransaction::packStream

https://github.com/LLNL/SAMRAI/blob/master/source/SAMRAI/xfer/RefineTimeTransaction.C#L161-L169

and that temporary patch seems not to be given a PatchGeometry.
Is that a normal behavior or a wrong expectation from our side that any patch should have a valid PatchGeometry?

Interestingly, when executed in serial, allocate() is not called in packstream but somewhere else, and our exception is not triggered, meaning that the patch to be allocated has a valid geometry.

**Comment by nselliott** [comment]
The actual behavior is that only Patches that exist on a PatchLevel will have a valid PatchGeometry.  Since these temporary Patches in RefineTimeTransaction are not on a PatchLevel, they don't have a PatchGeometry and that triggers your error.  I will make a note that this is something we need to make clear in the documentation.

In this context of time interpolation, the PatchData on the temporary Patch becomes the destination data in

```
timeInterpolate(
    hier::PatchData& dst_data,
    const hier::Box& where,
    const hier::BoxOverlap& overlap,
    const hier::PatchData& src_data_old,
    const hier::PatchData& src_data_new) const
```

All three PatchData objects should be defined on spatially identical Boxes, and the src objects exist on PatchLevels, so they should have valid Dx and XLower values that you could assign to `dst_data` inside your implementation of `timeInterpolate`.

You can verify my assumption that they are all on spatially identical Boxes by calling `getBox()` for each one and testing them with `Box::isSpatiallyEqual()`.

**Comment by nicolasaunai** [comment]
ok thanks for the quick answer. Closing.
