### ISSUE TITLE
smallest patch size sometimes smaller than max ghosts

### ISSUE THREAD

**Issue by PhilipDeegan** [LLNL/SAMRAI#171]
Hi there,

I've noticed sometimes, given specific mesh size and smallest/largest_patch_size configurations that sometimes we're getting patch sizes that are smaller than expected
 
For instance with "mpirun -n 2",  a 1d mesh of size 30, with smallest and largest_patch_size of 6, we are getting patches of size 3. This does not occur in serial, and also resolves in parallel when increasing the mesh size to 60. This is a configuration we are using for testing, so it's perhaps not valid.

Is there some way to make samrai error on setup if our configuration cannot be respected, or varies outside a certain accepted range?

allow_patches_smaller_than_ghostwidth and allow_patches_smaller_than_minimum_size_to_prevent_overlaps are default (false).

Thanks

**Comment by nselliott** [comment]
There are circumstances where the input values for the smallest and largest patch sizes cannot be strictly enforced, because sometimes the algorithms for box generation and load balancing run out of degrees of freedom to adjust the patch sizes to match all of the provided restrictions.  This is especially true when then the values for smallest and largest patch sizes are very near each other or equal, and also when the overall mesh is small.

We don't have a way to automatically force an error in these circumstances.  I would recommend adding checks on the patch sizes into your code after the hierarchy is generated if you need to verify that they match your expected parameters.

**Comment by PhilipDeegan** [comment]
ok thanks
