### ISSUE TITLE
segmentation fault in PatchHierarchy::computeRequiredConnectorWidths

### ISSUE THREAD

**Issue by nicolasaunai** [LLNL/SAMRAI#50]
in hier/PatchHierarchy.C

[https://github.com/LLNL/SAMRAI/blob/d3db96be466567e5c8c495b79ac4b84e92d60c52/source/SAMRAI/hier/PatchHierarchy.C#L596](url)

 first the vector `d_fine_connector_widths` is cleared
then if the `d_max_levels >1 ` the vector is resized and assigned with values
and then the first item of `d_fine_connector_widths` is accessed,  no matter what the value of `d_max_levels` is.

This leads to a segmentation fault in the (unlikely but possible) case where d_max_levels is not strictly greater than 1.

**Comment by davidbeckingsale** [comment]
Have you been able to trigger this segfault?

**Comment by nicolasaunai** [comment]
yep, well it depends...
On my mac I could not...

however on our continuous integration server which runs a fedora yes I did : 

 you can look [here](https://hephaistos.lpp.polytechnique.fr/teamcity/viewLog.html?buildId=35093&buildTypeId=SandBox_Phare_Build&tab=buildLog&guest=1) 

and search for "Segmentation fault" to find the error.

I guess it is kind of random as usual for segfaults.

What I found is that I forgot that d_max_levels was set to 1 in our input file but I was still making a finer level.... The segfault disappeared when I changed the input parameter to 2... nevertheless it seems the code should not access d_fine_connector_widths[0] after a clear() anyway. We don't really know what all this means so we could not propose a fix and PR it, sorry.

**Comment by nselliott** [comment]
Thanks for reporting this, as it is a genuine bug.

The declaration line

`   std::vector<IntVector> fine_connector_widths(0, d_fine_connector_widths[0]);`

is invalid if d_fine_connector_widths has been cleared to size zero.  But it is unnecessary to access d_fine_connector_widths[0] at all here, because the new vector declared here is constructed with size zero and thus doesn't need a default value argument.  So we should just do a default declaration:

`   std::vector<IntVector> fine_connector_widths;`

I'll go ahead and implement the fix.

**Comment by davidbeckingsale** [comment]
Fixed by #54
