### ISSUE TITLE
Does SAMRAI support geometry with curved boundaries?

### ISSUE THREAD

**Issue by ztdepztdep** [LLNL/SAMRAI#55]
Dear sir：
     Does SAMRAI support geometry with curved boundaries? I want to develop a FVM code based on adaptive multiblock structured grid system. 
Regards

**Comment by nselliott** [comment]
Yes, SAMRAI can support curved mesh geometries.  For this purpose we recommend storing your mesh point locations as arrays that are part of the state data of your code--you can use NodeVariable/NodeData to do this, or create your own data structures.  For the structured logical I-J-K coordinates of your mesh, you can use the geom::GridGeometry and hier::PatchGeometry classes directly rather than creating derived child classes.
