### ISSUE TITLE
CMake fails with -DENABLE_HDF5=Off

### ISSUE THREAD

**Issue by Dekken** [LLNL/SAMRAI#89]
Some tests are still trying to link to libhdf5

**Comment by Dekken** [comment]
I think this is merged/fixed yes?

**Comment by davidbeckingsale** [comment]
Yes, I believe that #90 fixed this.

**Comment by Dekken** [comment]
this is still the case

```
[ 26%] Built target testSilo
/usr/bin/ld: cannot find -lhdf5
```

**Comment by nselliott** [comment]
I haven't been able to reproduce this error, but I suspect that it stems from the explicit dependency on hdf5 in source/test/restartdb/CMakeLists.txt.  This isn't necessary, as these tests should inherit or not inherit the dependency on hdf5 from SAMRAI_tbox, depending on how the cmake build was configured.  I will prepare a fix.  @Dekken, if you would like to verify this for yourself before the fix is available, you can remove the blt hdf5 dependencies from source/test/restartdb/CMakeLists.txt to make it look like
 
```
blt_add_executable(
  NAME testHDF5
  SOURCES ${testHDF5_sources}
  DEPENDS_ON
    SAMRAI_hier
    SAMRAI_tbox)

blt_add_executable(
  NAME testHDF5AppFileOpen
  SOURCES ${testHDF5AppFileOpen_sources}
  DEPENDS_ON
    SAMRAI_hier
    SAMRAI_tbox)
```

**Comment by Dekken** [comment]
sure will do

**Comment by Dekken** [comment]
builds now
